package proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public final class ProductProtos {
  private ProductProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Brand_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Brand_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Category_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Category_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductSearchFilter_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductSearchFilter_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductSearchRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductSearchRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductSearchResonse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductSearchResonse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\"!\n\005Brand\022\n\n\002id\030\001 \002(\004\022\014\n\004" +
      "name\030\002 \002(\t\"$\n\010Category\022\n\n\002id\030\001 \002(\004\022\014\n\004na" +
      "me\030\002 \002(\t\"\370\001\n\007Product\022\n\n\002id\030\001 \002(\004\022\014\n\004name" +
      "\030\002 \002(\t\022\025\n\005brand\030\003 \002(\0132\006.Brand\022\033\n\010categor" +
      "y\030\004 \002(\0132\t.Category\022\r\n\005color\030\005 \001(\t\022\021\n\tsel" +
      "l_rate\030\006 \002(\004\022\020\n\010net_rate\030\007 \002(\004\022\020\n\010quanti" +
      "ty\030\010 \002(\r\022\023\n\013description\030\t \001(\t\022\016\n\006imgUrl\030" +
      "\n \001(\t\022\021\n\timageUrls\030\013 \003(\t\022!\n\017recommendati" +
      "ons\030\014 \003(\0132\010.Product\"m\n\023ProductSearchFilt" +
      "er\022\020\n\010brand_id\030\001 \001(\004\022\023\n\013category_id\030\002 \001(",
      "\004\022\031\n\021business_group_id\030\003 \001(\004\022\024\n\014product_" +
      "name\030\004 \001(\004\"_\n\024ProductSearchRequest\0223\n\025pr" +
      "oduct_search_filter\030\001 \001(\0132\024.ProductSearc" +
      "hFilter\022\022\n\nproduct_id\030\002 \003(\004\"1\n\024ProductSe" +
      "archResonse\022\031\n\007product\030\001 \001(\0132\010.ProductB\023" +
      "B\rProductProtosH\001P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Brand_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Brand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Brand_descriptor,
              new java.lang.String[] { "Id", "Name", });
          internal_static_Category_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Category_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Category_descriptor,
              new java.lang.String[] { "Id", "Name", });
          internal_static_Product_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Product_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Product_descriptor,
              new java.lang.String[] { "Id", "Name", "Brand", "Category", "Color", "SellRate", "NetRate", "Quantity", "Description", "ImgUrl", "ImageUrls", "Recommendations", });
          internal_static_ProductSearchFilter_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ProductSearchFilter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProductSearchFilter_descriptor,
              new java.lang.String[] { "BrandId", "CategoryId", "BusinessGroupId", "ProductName", });
          internal_static_ProductSearchRequest_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_ProductSearchRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProductSearchRequest_descriptor,
              new java.lang.String[] { "ProductSearchFilter", "ProductId", });
          internal_static_ProductSearchResonse_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_ProductSearchResonse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProductSearchResonse_descriptor,
              new java.lang.String[] { "Product", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
