// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public interface ProductSearchResonseOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .Product product = 1;
  /**
   * <code>optional .Product product = 1;</code>
   */
  boolean hasProduct();
  /**
   * <code>optional .Product product = 1;</code>
   */
  Product getProduct();
  /**
   * <code>optional .Product product = 1;</code>
   */
  ProductOrBuilder getProductOrBuilder();
}
